### ISSUE TITLE
Deployment fails during Haystack indexing

### ISSUE THREAD

**Issue by mhuyck** [greenelab/adage-server#250]
My attempt to deploy a test server was foiled on Friday by an error in the `python manage.py rebuild_index --noinput` step, which prepares search indexes via Haystack after the data are loaded.

The relevant output from the `fab` script is:

```
[adage@54.85.222.72] out: Removing all documents from your index because you said so.
[adage@54.85.222.72] out: INFO: DELETE http://127.0.0.1:9200/haystack [status:404 request:0.080s]
[adage@54.85.222.72] out: No handlers could be found for logger "elasticsearch.trace"
[adage@54.85.222.72] out: All documents removed.
[adage@54.85.222.72] out: Indexing 135 experiments
[adage@54.85.222.72] out: WARNING: GET /haystack/_mapping [status:404 request:0.005s]
[adage@54.85.222.72] out: INFO: PUT http://127.0.0.1:9200/haystack [status:200 request:0.672s]
[adage@54.85.222.72] out: INFO: PUT http://127.0.0.1:9200/haystack/_mapping/modelresult [status:200 request:0.181s]
[adage@54.85.222.72] out: INFO: POST http://127.0.0.1:9200/haystack/modelresult/_bulk [status:200 request:0.751s]
[adage@54.85.222.72] out: INFO: POST http://127.0.0.1:9200/haystack/_refresh [status:200 request:0.371s]
[adage@54.85.222.72] out: Indexing 1150 samples
[adage@54.85.222.72] out: [ERROR/MainProcess] Failed indexing 1 - 1000 (retry 5/5): The model '<Experiment: E-GEOD-9989>' does not have a model_attr 'all'. (pid 2119): The model '<Experiment: E-GEOD-9989>' does not have a model_attr 'all'.
[adage@54.85.222.72] out: Traceback (most recent call last):
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 84, in do_update
[adage@54.85.222.72] out:     backend.update(index, current_qs, commit=commit)
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/haystack/backends/elasticsearch_backend.py", line 168, in update
[adage@54.85.222.72] out:     prepped_data = index.full_prepare(obj)
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/haystack/indexes.py", line 208, in full_prepare
[adage@54.85.222.72] out:     self.prepared_data = self.prepare(obj)
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/haystack/indexes.py", line 199, in prepare
[adage@54.85.222.72] out:     self.prepared_data[field.index_fieldname] = field.prepare(obj)
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/haystack/fields.py", line 205, in prepare
[adage@54.85.222.72] out:     return self.convert(super(CharField, self).prepare(obj))
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/haystack/fields.py", line 88, in prepare
[adage@54.85.222.72] out:     values = self.resolve_attributes_lookup(current_objects, attrs)
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/haystack/fields.py", line 115, in resolve_attributes_lookup
[adage@54.85.222.72] out:     return self.resolve_attributes_lookup(current_objects_in_attr, attributes[1:])
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/haystack/fields.py", line 110, in resolve_attributes_lookup
[adage@54.85.222.72] out:     "The model '%s' does not have a model_attr '%s'." % (repr(current_object), attributes[0])
[adage@54.85.222.72] out: SearchFieldError: The model '<Experiment: E-GEOD-9989>' does not have a model_attr 'all'.
[adage@54.85.222.72] out: [ERROR/MainProcess] Error updating analyze using default 
[adage@54.85.222.72] out: Traceback (most recent call last):
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 214, in handle
[adage@54.85.222.72] out:     self.update_backend(label, using)
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 257, in update_backend
[adage@54.85.222.72] out:     commit=self.commit, max_retries=self.max_retries)
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 84, in do_update
[adage@54.85.222.72] out:     backend.update(index, current_qs, commit=commit)
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/haystack/backends/elasticsearch_backend.py", line 168, in update
[adage@54.85.222.72] out:     prepped_data = index.full_prepare(obj)
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/haystack/indexes.py", line 208, in full_prepare
[adage@54.85.222.72] out:     self.prepared_data = self.prepare(obj)
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/haystack/indexes.py", line 199, in prepare
[adage@54.85.222.72] out:     self.prepared_data[field.index_fieldname] = field.prepare(obj)
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/haystack/fields.py", line 205, in prepare
[adage@54.85.222.72] out:     return self.convert(super(CharField, self).prepare(obj))
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/haystack/fields.py", line 88, in prepare
[adage@54.85.222.72] out:     values = self.resolve_attributes_lookup(current_objects, attrs)
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/haystack/fields.py", line 115, in resolve_attributes_lookup
[adage@54.85.222.72] out:     return self.resolve_attributes_lookup(current_objects_in_attr, attributes[1:])
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/haystack/fields.py", line 110, in resolve_attributes_lookup
[adage@54.85.222.72] out:     "The model '%s' does not have a model_attr '%s'." % (repr(current_object), attributes[0])
[adage@54.85.222.72] out: SearchFieldError: The model '<Experiment: E-GEOD-9989>' does not have a model_attr 'all'.
[adage@54.85.222.72] out: Traceback (most recent call last):
[adage@54.85.222.72] out:   File "manage.py", line 10, in <module>
[adage@54.85.222.72] out:     execute_from_command_line(sys.argv)
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
[adage@54.85.222.72] out:     utility.execute()
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
[adage@54.85.222.72] out:     self.fetch_command(subcommand).run_from_argv(self.argv)
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
[adage@54.85.222.72] out:     self.execute(*args, **cmd_options)
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
[adage@54.85.222.72] out:     output = self.handle(*args, **options)
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/haystack/management/commands/rebuild_index.py", line 37, in handle
[adage@54.85.222.72] out:     call_command('update_index', **options)
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 120, in call_command
[adage@54.85.222.72] out:     return command.execute(*args, **defaults)
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
[adage@54.85.222.72] out:     output = self.handle(*args, **options)
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 214, in handle
[adage@54.85.222.72] out:     self.update_backend(label, using)
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 257, in update_backend
[adage@54.85.222.72] out:     commit=self.commit, max_retries=self.max_retries)
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 84, in do_update
[adage@54.85.222.72] out:     backend.update(index, current_qs, commit=commit)
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/haystack/backends/elasticsearch_backend.py", line 168, in update
[adage@54.85.222.72] out:     prepped_data = index.full_prepare(obj)
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/haystack/indexes.py", line 208, in full_prepare
[adage@54.85.222.72] out:     self.prepared_data = self.prepare(obj)
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/haystack/indexes.py", line 199, in prepare
[adage@54.85.222.72] out:     self.prepared_data[field.index_fieldname] = field.prepare(obj)
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/haystack/fields.py", line 205, in prepare
[adage@54.85.222.72] out:     return self.convert(super(CharField, self).prepare(obj))
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/haystack/fields.py", line 88, in prepare
[adage@54.85.222.72] out:     values = self.resolve_attributes_lookup(current_objects, attrs)
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/haystack/fields.py", line 115, in resolve_attributes_lookup
[adage@54.85.222.72] out:     return self.resolve_attributes_lookup(current_objects_in_attr, attributes[1:])
[adage@54.85.222.72] out:   File "/home/adage/.virtualenvs/adage/local/lib/python2.7/site-packages/haystack/fields.py", line 110, in resolve_attributes_lookup
[adage@54.85.222.72] out:     "The model '%s' does not have a model_attr '%s'." % (repr(current_object), attributes[0])
[adage@54.85.222.72] out: haystack.exceptions.SearchFieldError: The model '<Experiment: E-GEOD-9989>' does not have a model_attr 'all'.
[adage@54.85.222.72] out: 


Fatal error: run() received nonzero return code 1 while executing!

Requested: python manage.py rebuild_index --noinput
Executed: /bin/bash -l -c "cd /home/adage/adage-server/adage >/dev/null && source /home/adage/.virtualenvs/adage/bin/activate && python manage.py rebuild_index --noinput"

Aborting.
```

**Comment by mhuyck** [comment]
I have done enough digging (reran the script, googled) to determine that this is not a sporadic failure, as we have sometimes seen with the current deployment setup. The error was related to Haystack so I looked for changes there and the most recent thing we did was update our `requirements.txt` to use `django-haystack==2.6.0`. My development instance was still on the older version and, sure enough, when I updated haystack I got the same error.

@rzelayafavila: I believe this update was made to simplify the Docker migration, right? You should be aware that this issue will probably block deployment via Docker as well until we have it sorted out.

**Comment by rzelayafavila** [comment]
@mhuyck : Ok got it - yes, the upgrade of django-haystack to `2.6.0` was necessary for the docker deployment. We will have to figure out what is going on.

**Comment by mhuyck** [comment]
I think I see the issue. Line 28 of `search_indexes.py` attempts to make the `Sample` index include a list of all the `Experiment`s in which it appears. I think this line never worked. It used to fail silently and now Haystack has better error reporting so it explicitly complains that it can't find the `all` attribute on an `Experiment`. (True! But we were trying to use the *reverse relation's* `all()` *method* to get a list of experiments.)

I think the way to fix this is to use a `prepare_experiments` method in `search_indexes.py`, following the example in the docs here: http://django-haystack.readthedocs.io/en/latest/searchindex_api.html#prepare-foo-self-object

**Comment by mhuyck** [comment]
Actually, our goal is to be able to find `Sample`s when search terms are matched in the corresponding `Experiment` description, and just listing Experiment IDs doesn't do that either. Maybe the template in `analyze/templates/search/indexes/analyze/sample_text.txt` is a better place for this, and we can remove the `experiments` attribute entirely.
